-- Registro Clínico: esquema relacional, Auth, RLS y tiempo real.
-- Ejecutar con Supabase CLI (`supabase db push`) o desde el SQL Editor.
create extension if not exists pgcrypto;

do $$ begin
  create type public.rol_aplicacion as enum ('Administrador', 'Médico', 'Auxiliar');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.responsable_autorizado as enum ('Doctor', 'Auxiliar', 'Ambos');
exception when duplicate_object then null; end $$;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  nombre_completo text not null check (length(trim(nombre_completo)) > 0),
  rol public.rol_aplicacion not null default 'Auxiliar',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.personal_consultorio (
  id uuid primary key default gen_random_uuid(),
  nombre_completo text not null unique check (length(trim(nombre_completo)) > 0),
  cargo text not null check (length(trim(cargo)) > 0),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.servicios (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique check (length(trim(nombre)) > 0),
  precio numeric(12,2) not null default 0 check (precio >= 0),
  descripcion text not null default '',
  requiere_consulta_medica boolean not null default false,
  genera_historia_clinica boolean not null default false,
  responsable_autorizado public.responsable_autorizado not null default 'Ambos',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.pacientes (
  id uuid primary key default gen_random_uuid(),
  legacy_id bigint generated by default as identity unique,
  nombre text not null check (length(trim(nombre)) > 0),
  apellido text not null default '',
  ci text,
  fecha_nacimiento date,
  genero text,
  telefono text,
  email text,
  direccion text,
  registrado_en date not null default current_date,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.historias_clinicas (
  id uuid primary key default gen_random_uuid(),
  paciente_id uuid not null unique references public.pacientes(id) on delete cascade,
  grupo_sanguineo text not null default '',
  antecedentes_personales text not null default '',
  antecedentes_quirurgicos text not null default '',
  antecedentes_familiares text not null default '',
  antecedentes_alergicos text not null default '',
  medicamentos_actuales text not null default '',
  habitos text not null default '',
  hospitalizaciones text not null default '',
  enfermedades_cronicas text not null default '',
  antecedentes_gineco_obstetricos text not null default '',
  inmunizaciones text not null default '',
  notas text not null default '',
  creado_por uuid references public.usuarios(id) on delete set null,
  actualizado_por uuid references public.usuarios(id) on delete set null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.atenciones (
  id uuid primary key default gen_random_uuid(),
  legacy_id bigint generated by default as identity unique,
  paciente_id uuid not null references public.pacientes(id) on delete restrict,
  servicio_id uuid references public.servicios(id) on delete set null,
  historia_clinica_id uuid references public.historias_clinicas(id) on delete set null,
  responsable_id uuid references public.personal_consultorio(id) on delete set null,
  registrado_por uuid references public.usuarios(id) on delete set null,
  fecha_hora timestamptz not null default now(),
  estado text not null default 'Pendiente'
    check (estado in ('Pendiente','Pendiente de consulta','En consulta','Finalizada','Cancelada')),
  servicio_nombre_snapshot text not null,
  precio_snapshot numeric(12,2) not null default 0 check (precio_snapshot >= 0),
  responsable_nombre_snapshot text,
  registrado_por_nombre_snapshot text not null default '',
  motivo text not null default '',
  evolucion text not null default '',
  diagnostico text not null default '',
  tratamiento text not null default '',
  receta text not null default '',
  indicaciones text not null default '',
  proximo_control date,
  datos_clinicos jsonb not null default '{}'::jsonb check (jsonb_typeof(datos_clinicos) = 'object'),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists pacientes_nombre_idx on public.pacientes (lower(nombre), lower(apellido));
create unique index if not exists pacientes_ci_unica_idx on public.pacientes (ci) where ci is not null and trim(ci) <> '';
create index if not exists servicios_activos_idx on public.servicios (activo, nombre);
create index if not exists personal_activo_idx on public.personal_consultorio (activo, nombre_completo);
create index if not exists atenciones_cola_idx on public.atenciones (estado, fecha_hora);
create index if not exists atenciones_paciente_idx on public.atenciones (paciente_id, fecha_hora desc);
create index if not exists atenciones_servicio_idx on public.atenciones (servicio_id, fecha_hora desc);
create index if not exists atenciones_responsable_idx on public.atenciones (responsable_id, fecha_hora desc);
create index if not exists atenciones_registrador_idx on public.atenciones (registrado_por, fecha_hora desc);

create or replace function public.actualizar_timestamp()
returns trigger language plpgsql set search_path = public as $$
begin new.actualizado_en = now(); return new; end $$;

do $$ declare tabla text; begin
  foreach tabla in array array['usuarios','personal_consultorio','servicios','pacientes','historias_clinicas','atenciones']
  loop
    execute format('drop trigger if exists actualizar_timestamp on public.%I', tabla);
    execute format('create trigger actualizar_timestamp before update on public.%I for each row execute function public.actualizar_timestamp()', tabla);
  end loop;
end $$;

create or replace function public.crear_usuario_auth()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.usuarios (id, email, nombre_completo, rol)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(nullif(trim(new.raw_user_meta_data->>'nombre_completo'), ''), split_part(coalesce(new.email, 'Usuario'), '@', 1)),
    'Auxiliar'
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists crear_usuario_auth on auth.users;
create trigger crear_usuario_auth after insert on auth.users
for each row execute function public.crear_usuario_auth();

create or replace function public.rol_actual()
returns public.rol_aplicacion language sql stable security definer set search_path = public as $$
  select rol from public.usuarios where id = auth.uid() and activo
$$;

create or replace function public.obtener_o_crear_historia(paciente_legacy_id bigint)
returns public.historias_clinicas language plpgsql security invoker set search_path = public as $$
declare resultado public.historias_clinicas;
begin
  insert into public.historias_clinicas (paciente_id, creado_por, actualizado_por)
  select p.id, auth.uid(), auth.uid() from public.pacientes p where p.legacy_id = paciente_legacy_id
  on conflict (paciente_id) do update set paciente_id = excluded.paciente_id
  returning * into resultado;
  if resultado.id is null then raise exception 'Paciente no encontrado'; end if;
  return resultado;
end $$;

alter table public.usuarios enable row level security;
alter table public.personal_consultorio enable row level security;
alter table public.servicios enable row level security;
alter table public.pacientes enable row level security;
alter table public.historias_clinicas enable row level security;
alter table public.atenciones enable row level security;

create policy "usuarios lectura propia o admin" on public.usuarios for select to authenticated
using (id = auth.uid() or public.rol_actual() = 'Administrador');
create policy "usuarios administra admin" on public.usuarios for update to authenticated
using (public.rol_actual() = 'Administrador') with check (public.rol_actual() = 'Administrador');

create policy "servicios lectura autenticada" on public.servicios for select to authenticated using (true);
create policy "servicios administra admin" on public.servicios for all to authenticated
using (public.rol_actual() = 'Administrador') with check (public.rol_actual() = 'Administrador');
create policy "personal lectura autenticada" on public.personal_consultorio for select to authenticated using (true);
create policy "personal administra admin" on public.personal_consultorio for all to authenticated
using (public.rol_actual() = 'Administrador') with check (public.rol_actual() = 'Administrador');

create policy "pacientes lectura personal" on public.pacientes for select to authenticated using (public.rol_actual() is not null);
create policy "pacientes alta personal" on public.pacientes for insert to authenticated with check (public.rol_actual() is not null);
create policy "pacientes edicion clinica" on public.pacientes for update to authenticated
using (public.rol_actual() in ('Administrador','Médico'))
with check (public.rol_actual() in ('Administrador','Médico'));
create policy "pacientes elimina admin" on public.pacientes for delete to authenticated
using (public.rol_actual() = 'Administrador');

create policy "historias lectura clinica" on public.historias_clinicas for select to authenticated
using (public.rol_actual() in ('Administrador','Médico'));
create policy "historias alta clinica" on public.historias_clinicas for insert to authenticated
with check (public.rol_actual() in ('Administrador','Médico'));
create policy "historias edicion clinica" on public.historias_clinicas for update to authenticated
using (public.rol_actual() in ('Administrador','Médico'))
with check (public.rol_actual() in ('Administrador','Médico'));

create policy "atenciones lectura por rol" on public.atenciones for select to authenticated
using (
  public.rol_actual() in ('Administrador','Médico')
  or (
    public.rol_actual() = 'Auxiliar'
    and (
      estado in ('Pendiente','Pendiente de consulta')
      or not exists (
        select 1 from public.servicios s
        where s.id = atenciones.servicio_id and s.requiere_consulta_medica
      )
    )
  )
);
create policy "atenciones alta personal" on public.atenciones for insert to authenticated
with check (public.rol_actual() is not null and (registrado_por = auth.uid() or registrado_por is null));
create policy "atenciones edicion por rol" on public.atenciones for update to authenticated
using (
  public.rol_actual() in ('Administrador','Médico')
  or (
    public.rol_actual() = 'Auxiliar'
    and not exists (
      select 1 from public.servicios s
      where s.id = atenciones.servicio_id and s.requiere_consulta_medica
    )
  )
)
with check (
  public.rol_actual() in ('Administrador','Médico')
  or (
    public.rol_actual() = 'Auxiliar'
    and not exists (
      select 1 from public.servicios s
      where s.id = atenciones.servicio_id and s.requiere_consulta_medica
    )
  )
);
create policy "atenciones elimina admin" on public.atenciones for delete to authenticated
using (public.rol_actual() = 'Administrador');

grant execute on function public.obtener_o_crear_historia(bigint) to authenticated;

insert into public.servicios
  (nombre, precio, descripcion, requiere_consulta_medica, genera_historia_clinica, responsable_autorizado)
values
  ('Consulta médica', 0, '', true, true, 'Doctor'),
  ('Inyectable', 0, '', false, false, 'Auxiliar'),
  ('Curación', 0, '', false, false, 'Auxiliar'),
  ('Nebulización', 0, '', false, false, 'Auxiliar'),
  ('Sueroterapia', 0, '', false, false, 'Auxiliar'),
  ('Anticonceptivos', 0, '', false, false, 'Auxiliar'),
  ('Procedimiento estético', 0, '', false, false, 'Ambos'),
  ('Podología', 0, '', false, false, 'Ambos'),
  ('Otro procedimiento', 0, '', false, false, 'Ambos')
on conflict (nombre) do nothing;

insert into public.personal_consultorio (nombre_completo, cargo)
values
  ('Dr. Jeason Flores', 'Doctor'),
  ('Aux. Carmen', 'Auxiliar'),
  ('Aux. Jeniffer', 'Auxiliar'),
  ('Aux. Jhelen', 'Auxiliar')
on conflict (nombre_completo) do nothing;

do $$ declare tabla text; begin
  foreach tabla in array array['servicios','personal_consultorio','pacientes','historias_clinicas','atenciones']
  loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', tabla);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;
