-- MedSolution: Agenda como fuente oficial de las atenciones.
-- Crea citas, enlaza las atenciones existentes y mantiene ambos estados sincronizados.

begin;

create table if not exists public.citas (
  id uuid primary key default gen_random_uuid(),
  legacy_id bigint generated by default as identity unique,
  paciente_id uuid not null references public.pacientes(id) on delete restrict,
  servicio_id uuid references public.servicios(id) on delete set null,
  fecha_hora timestamptz not null,
  profesional text not null default '',
  observaciones text not null default '',
  estado text not null default 'Pendiente'
    check (estado in ('Pendiente','Programada','Confirmada','En Atención','Reprogramada','Atendida','Cancelada')),
  creado_por_nombre text not null default '',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

alter table public.atenciones
  add column if not exists cita_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'atenciones_cita_id_fkey'
  ) then
    alter table public.atenciones
      add constraint atenciones_cita_id_fkey
      foreign key (cita_id) references public.citas(id) on delete restrict;
  end if;
end
$$;

create index if not exists citas_fecha_idx on public.citas (fecha_hora);
create index if not exists citas_estado_fecha_idx on public.citas (estado, fecha_hora);
create index if not exists citas_paciente_idx on public.citas (paciente_id, fecha_hora desc);
create index if not exists citas_servicio_idx on public.citas (servicio_id, fecha_hora desc);
create unique index if not exists atenciones_cita_unica_idx
  on public.atenciones (cita_id) where cita_id is not null;

-- Toda atención histórica recibe su cita equivalente una sola vez.
do $$
declare
  atencion record;
  nueva_cita uuid;
begin
  for atencion in
    select * from public.atenciones where cita_id is null order by fecha_hora, creado_en
  loop
    insert into public.citas (
      paciente_id, servicio_id, fecha_hora, profesional, observaciones,
      estado, creado_por_nombre, creado_en, actualizado_en
    ) values (
      atencion.paciente_id,
      atencion.servicio_id,
      atencion.fecha_hora,
      coalesce(atencion.responsable_nombre_snapshot, ''),
      coalesce(atencion.motivo, ''),
      case atencion.estado
        when 'En consulta' then 'En Atención'
        when 'Finalizada' then 'Atendida'
        when 'Cancelada' then 'Cancelada'
        else 'Pendiente'
      end,
      coalesce(atencion.registrado_por_nombre_snapshot, ''),
      atencion.creado_en,
      atencion.actualizado_en
    ) returning id into nueva_cita;

    update public.atenciones set cita_id = nueva_cita where id = atencion.id;
  end loop;
end
$$;

alter table public.atenciones alter column cita_id set not null;

create or replace function public.sincronizar_estado_cita()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.citas set estado = 'Cancelada' where id = old.cita_id;
    return old;
  end if;
  update public.citas
  set estado = case new.estado
    when 'En consulta' then 'En Atención'
    when 'Finalizada' then 'Atendida'
    when 'Cancelada' then 'Cancelada'
    else 'Pendiente'
  end
  where id = new.cita_id;
  return new;
end
$$;

drop trigger if exists sincronizar_estado_cita on public.atenciones;
create trigger sincronizar_estado_cita
after insert or update of estado, cita_id on public.atenciones
for each row execute function public.sincronizar_estado_cita();

drop trigger if exists sincronizar_eliminacion_cita on public.atenciones;
create trigger sincronizar_eliminacion_cita
after delete on public.atenciones
for each row execute function public.sincronizar_estado_cita();

create or replace function public.sincronizar_atencion_desde_cita()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  -- Evita recursión cuando el cambio se originó en public.atenciones.
  if pg_trigger_depth() > 1 then return new; end if;

  update public.atenciones as a
  set fecha_hora = new.fecha_hora,
      servicio_id = new.servicio_id,
      estado = case new.estado
        when 'Pendiente' then 'Pendiente'
        when 'En Atención' then 'En consulta'
        when 'Atendida' then 'Finalizada'
        when 'Cancelada' then 'Cancelada'
        else a.estado
      end
  where a.cita_id = new.id;
  return new;
end
$$;

drop trigger if exists sincronizar_atencion_desde_cita on public.citas;
create trigger sincronizar_atencion_desde_cita
after update of estado, fecha_hora, servicio_id on public.citas
for each row execute function public.sincronizar_atencion_desde_cita();

drop trigger if exists actualizar_timestamp on public.citas;
create trigger actualizar_timestamp
before update on public.citas
for each row execute function public.actualizar_timestamp();

alter table public.citas enable row level security;
grant select, insert, update, delete on table public.citas to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists medsolution_citas_select on public.citas;
drop policy if exists medsolution_citas_insert on public.citas;
drop policy if exists medsolution_citas_update on public.citas;
drop policy if exists medsolution_citas_delete on public.citas;

create policy medsolution_citas_select on public.citas
for select to anon, authenticated using (true);
create policy medsolution_citas_insert on public.citas
for insert to anon, authenticated with check (true);
create policy medsolution_citas_update on public.citas
for update to anon, authenticated using (true) with check (true);
create policy medsolution_citas_delete on public.citas
for delete to anon, authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.citas;
exception
  when duplicate_object then null;
  when undefined_object then null;
end
$$;

commit;
